#!/bin/sh

echo "
    Alsa Mixer Gui - v1 - Created by KuLuSz y2019 m10 d05
"
CC=$(cat /etc/asound.conf | grep "pcm\.card" | cut -f2 -d' ') #current card
CD=$(cat /etc/asound.conf | grep "pcm\.device" | cut -f2 -d' ') #current device
CS=$(aplay -l | grep "card $CC:" | grep " device $CD:" | cut -f2 -d':' | cut -f1 -d'[')
CS2=$(aplay -l | grep "card $CC:" | grep " device $CD:" | cut -f3 -d':' | cut -f1 -d'[')

mkdir -p /tmp/AMG
echo '' > /tmp/AMG/mixer_play_gui
echo '' > /tmp/AMG/mixer_rec_gui
echo '' > /tmp/AMG/mixer_switch_gui
echo '' > /tmp/AMG/mixer_switch_items

gui_func(){
  SWON=$(echo $9 | cut -f1 -d'|')
  SWOFF=$(echo $9 | cut -f2 -d'|')
  CH="$(echo "$1" | sed 's/_/ /g')"
  echo '   <vbox tooltip-text="'$1' channel">
     <text height-request="3"> <label>ˇ</label> </text>
     <hbox homogeneous="true">
      <checkbox draw_indicator="false" active="'$4'" width-request="85">
       <label>'$CH'</label>
       <variable>'$1'M</variable>
       <sensitive>'$5'</sensitive>
        <action condition="active_is_true('$1'M)">amixer -q set "'$CH'" $'$1'L%,$'$1'R% '$SWON' &</action>
        <action condition="active_is_false('$1'M)">amixer -q set "'$CH'" $'$1'L%,$'$1'R% '$SWOFF' &</action>
      </checkbox>
     </hbox>

     <hbox homogeneous="true" width-request="60">
     
       <vscale width-request="70" height-request="120" range-step="25" inverted="true" auto-refresh="true">
        <default>'$2'</default>
        <variable>'$1'L</variable>
        <input>cat /tmp/AMG/'$1'1</input>
        <action condition="active_is_true('$1'C)">echo $'$1'L > /tmp/AMG/'$1'2</action>
        <action condition="active_is_true('$1'C)">refresh:'$1'R</action>
        <action>amixer -q set "'$CH'" $'$1'L%,$'$1'R% &</action>        
       </vscale>
       
       <vscale width-request="70" height-request="120" range-step="25" inverted="true" auto-refresh="true">
        <default>'$3'</default>
        <variable>'$1'R</variable>
        <input>cat /tmp/AMG/'$1'2</input>
        <action condition="active_is_true('$1'C)">echo $'$1'R > /tmp/AMG/'$1'1</action>
        <action condition="active_is_true('$1'C)">refresh:'$1'L</action>
        <action>amixer -q set "'$CH'" $'$1'L%,$'$1'R% &</action>
       </vscale>
       
      </hbox>
      <hbox space-expand="true">
       <text height-request="14" width-request="1"> <label>ˇ</label> </text>
       <text> <label>L</label> </text>
       <checkbox draw_indicator="false" active="'$6'" height-request="18">
        <label>"="</label>
        <variable>'$1'C</variable>
        <visible>'$7'</visible>
       </checkbox>
       <text> <label>R</label> </text>
       <text height-request="14" width-request="1"> <label>ˇ</label> </text>
      </hbox>
   </vbox>
    <vseparator>
    </vseparator>
   ' >> $8
   echo "$2" > /tmp/AMG/${1}1
   echo "$3" > /tmp/AMG/${1}2
}
export -f gui_func

switch_func (){
	CH="$(echo "$1" | sed 's/_/ /g')"
	CH2="$(echo "$1" | sed 's/-//g')"
	for i in `echo "$3" | sed 's/:/ /g'`;do
	echo '<item>'$i'</item>' >> /tmp/AMG/mixer_switch_items
	done
	echo ' <vbox tooltip-text="'$CH' channel">
	  <text> <label>'$CH'</label> </text>
	  <hbox>
	   <comboboxtext width-request="100">
       <variable>'$CH2'_ITEM</variable>
       <default>'$2'</default>
	   '`cat /tmp/AMG/mixer_switch_items`'
	   <action>amixer -q set "'$CH'" "$'$CH2'_ITEM" &</action>
      </comboboxtext>
	  </hbox>
     </vbox>
    <vseparator>
    </vseparator>
	' >> /tmp/AMG/mixer_switch_gui
	echo '' > /tmp/AMG/mixer_switch_items
}
export -f switch_func

amixer | while read line;do
if [ "$(echo "$line" | grep "Simple mixer control")" ];then
    CH="$(echo "$line" | cut -f2 -d"'" | cut -f1 -d"'" | sed 's/ /_/g')"
elif [ "$(echo "$line" | grep "Capabilities")" ];then
    SW=""
    if [ ! -z "$(echo "$line" | grep "cvolume\|cswitch")" -o ! -z "$(echo "$line" | grep ": volume")"  ];then
    OF="/tmp/AMG/mixer_rec_gui"
    SW="cap|nocap"
    elif [ ! -z "$(echo "$line" | grep " pvolume \| pswitch ")" ];then
    OF="/tmp/AMG/mixer_play_gui"
    SW="unmute|mute"
    elif [ ! -z "$(echo "$line" | grep " enum ")" ];then
    OF="/tmp/AMG/mixer_switch_gui"
    fi
elif [ ! -z "$(echo "$line" | grep "Mono:" | cut -f2 -d':')" ];then
    L="$(echo "$line" | cut -f2 -d'[' | cut -f1 -d'%')"
    R="$L"
    CVIS="false"
    C="true"
    if [ "$(echo "$line" | cut -f4 -d'[' | cut -f1 -d']')" == "on" ];then
    ON="true"
    VIS="true"
    elif [ "$(echo "$line" | cut -f4 -d'[' | cut -f1 -d']')" == "off" ];then
    ON="false"
    VIS="true"
    else
    ON="true"
    VIS="false"
    fi
    gui_func $CH $L $R $ON $VIS $C $CVIS $OF $SW
elif [ "$(echo "$line" | grep "Front Left:" | cut -f2 -d':')" ];then
    L="$(echo "$line" | cut -f2 -d'[' | cut -f1 -d'%')"
    if [ "$(echo "$line" | cut -f4 -d'[' | cut -f1 -d']')" == "on" ];then
    ON="true"
    VIS="true"
    elif [ "$(echo "$line" | cut -f4 -d'[' | cut -f1 -d']')" == "off" ];then
    ON="false"
    VIS="true"
    else
    ON="true"
    VIS="false"
    fi
elif [ "$(echo "$line" | grep "Front Right:" | cut -f2 -d':')" ];then
    R="$(echo "$line" | cut -f2 -d'[' | cut -f1 -d'%')"
    CVIS="true"
    [ "$R" == "$L" ]&&	C="true" || C="false"
    gui_func $CH $L $R $ON $VIS $C $CVIS $OF $SW
elif [ "$(echo "$line" | grep "Items:" | cut -f2 -d':')" ];then
   ITEMS="$(echo "$line" | cut -f2 -d':' | sed "s/'//g" | sed "s/ /:/g")"
elif [ "$(echo "$line" | grep "Item0:" | cut -f2 -d':')" ];then
   ITEM0="$(echo "$line" | cut -f2 -d':' | sed "s/'//g" | sed "s/ //g")"
   switch_func $CH $ITEM0 $ITEMS
fi
done

PLAY_GUI="$(cat /tmp/AMG/mixer_play_gui)"
REC_GUI="$(cat /tmp/AMG/mixer_rec_gui)"
SWITCH_GUI="$(cat /tmp/AMG/mixer_switch_gui)"

export MIXER='<window title="AMG - Alsa mixer gui"  image-name="/usr/share/pixmaps/sound_mixer.svg">
<vbox width-request="600">
 <notebook labels="Playback|Record">
   <vbox height-request="215" homogeneous="true">
    <hbox scrollable="true" hscrollbar-policy="1" space-expand="true">
    '$PLAY_GUI'
    </hbox>
   </vbox>
   <vbox height-request="215" homogeneous="true">
    <hbox scrollable="true" hscrollbar-policy="1"  space-expand="true">
    '$REC_GUI'
    </hbox>
   </vbox>
 </notebook>
 <hbox space-expand="true">
  <vbox height-request="70" width-request="410">
   <hbox scrollable="true" hscrollbar-policy="1" vscrollbar-policy="2" space-expand="true">
    '$SWITCH_GUI'
    <text height-request="1" width-request="1"> <label>ˇ</label> </text>
   </hbox>
  </vbox>
  <text use-markup="true"> <label>"<b>'$CS' - '$CS2'</b>"</label> </text> 
 </hbox> 
</vbox>
</window>'
eval "$(gtkdialog --program=MIXER --center)"
[ "$EXIT" == "abort" ]&& rm -r /tmp/AMG
